const data = [
  {
    id: 1,
    title: 'Ceres',
    age: '14 000 000',
    weight: '5,972E24',
    type: 'blue',
    star: 'Nembus',
    resources: '50%',
    cost: '8',
    img: '../img/1.png',
    value: 'quadrillion',
  },
  {
    id: 2,
    title: 'Pallas',
    age: '13 000 000',
    weight: '6,972E24',
    type: 'red',
    star: 'Alpheratz',
    resources: '40%',
    cost: '1',
    img: '../img/2.png',
    value: 'billion',
  },
  {
    id: 3,
    title: 'Juno',
    age: '12 000 000',
    weight: '7,972E24',
    type: 'green',
    star: 'Mirach',
    resources: '30%',
    cost: '2',
    img: '../img/3.png',
    value: 'quadrillion',
  },
  {
    id: 4,
    title: 'Vesta',
    age: '11 000 000',
    weight: '8,972E24',
    type: 'blue',
    star: 'Almach',
    resources: '20%',
    cost: '3',
    img: '../img/4.png',
    value: 'billion',
  },
  {
    id: 5,
    title: 'Astraea',
    age: '10 000 000',
    weight: '9,972E24',
    type: 'red',
    star: 'Adhil',
    resources: '10%',
    cost: '4',
    img: '../img/5.png',
    value: 'million',
  },
  {
    id: 6,
    title: 'Hebe',
    age: '9 000 000',
    weight: '10,972E24',
    type: 'green',
    star: 'Titawin',
    resources: '60%',
    cost: '5',
    img: '../img/6.png',
    value: 'billion',
  },
  {
    id: 7,
    title: 'Iris',
    age: '8 000 000',
    weight: '11,972E24',
    type: 'blue',
    star: 'Castor',
    resources: '70%',
    cost: '6',
    img: '../img/7.png',
    value: 'quadrillion',
  },
  {
    id: 8,
    title: 'Flora',
    age: '7 000 000',
    weight: '12,972E24',
    type: 'red',
    star: 'Pollux',
    resources: '80%',
    cost: '7',
    img: '../img/8.png',
    value: 'billion',
  },
  {
    id: 9,
    title: 'Metis',
    age: '6 000 000',
    weight: '13,972E24',
    type: 'green',
    star: 'Wasat',
    resources: '90%',
    cost: '8',
    img: '../img/9.png',
    value: 'million',
  },
  {
    id: 10,
    title: 'Parthenope',
    age: '5 000 000',
    weight: '14,972E24',
    type: 'blue',
    star: 'Propus',
    resources: '100%',
    cost: '9',
    img: '../img/10.png',
    value: 'billion',
  },
]