const cardData = [
  {
    id: 1,
    title: 'Ceres',
    age: '14000000',
    weight: '5,972E24',
    type: 'blue',
    star: 'Nembus',
    resources: '50%',
    cost: '8',
    img: 'https://officialpsds.com/imageview/7l/0l/7l0lm0_large.png?1521316541',
    value: 'quadrillion',
  },
  {
    id: 2,
    title: 'Pallas',
    age: '13000000',
    weight: '6,972E24',
    type: 'red',
    star: 'Alpheratz',
    resources: '40%',
    cost: '1',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Bringer_of_War_Planet.png',
    value: 'billion',
  },
  {
    id: 3,
    title: 'Juno',
    age: '12000000',
    weight: '7,972E24',
    type: 'green',
    star: 'Mirach',
    resources: '30%',
    cost: '2',
    img: 'https://png.monster/wp-content/uploads/2022/07/png.monster-843.png',
    value: 'quadrillion',
  },
  {
    id: 4,
    title: 'Vesta',
    age: '14000000',
    weight: '8,972E24',
    type: 'blue',
    star: 'Almach',
    resources: '20%',
    cost: '3',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Populated_Planet.png/1024px-Populated_Planet.png',
    value: 'billion',
  },
  {
    id: 5,
    title: 'Astraea',
    age: '10000000',
    weight: '9,972E24',
    type: 'red',
    star: 'Adhil',
    resources: '10%',
    cost: '4',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ice_planet.png/1200px-Ice_planet.png',
    value: 'million',
  },
  {
    id: 6,
    title: 'Hebe',
    age: '9000000',
    weight: '10,972E24',
    type: 'green',
    star: 'Titawin',
    resources: '60%',
    cost: '5',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Gajillion_Islands_Planet.png',
    value: 'billion',
  },
  {
    id: 7,
    title: 'Iris',
    age: '8000000',
    weight: '11,972E24',
    type: 'blue',
    star: 'Castor',
    resources: '70%',
    cost: '6',
    img: 'https://images.pngnice.com/download/2007/Space-Planet-PNG-Photos.png',
    value: 'quadrillion',
  },
  {
    id: 8,
    title: 'Flora',
    age: '14000000',
    weight: '12,972E24',
    type: 'red',
    star: 'Pollux',
    resources: '80%',
    cost: '7',
    img: 'https://www.pngkit.com/png/full/288-2881214_1-photos-sci-fi-planet-png.png',
    value: 'billion',
  },
  {
    id: 9,
    title: 'Metis',
    age: '6000000',
    weight: '13,972E24',
    type: 'green',
    star: 'Wasat',
    resources: '90%',
    cost: '8',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Bringer_of_War_Planet.png',
    value: 'million',
  },
  {
    id: 10,
    title: 'Parthenope',
    age: '5000000',
    weight: '14,972E24',
    type: 'blue',
    star: 'Propus',
    resources: '100%',
    cost: '9',
    img: 'https://pngimg.com/uploads/mars_planet/mars_planet_PNG28.png',
    value: 'billion',
  },
  {
    id: 11,
    title: 'Nysa',
    age: '10000000',
    weight: '11,972E24',
    type: 'blue',
    star: 'Castor',
    resources: '70%',
    cost: '6',
    img: 'https://images.pngnice.com/download/2007/Space-Planet-PNG-Photos.png',
    value: 'quadrillion',
  },
  {
    id: 12,
    title: 'Urania',
    age: '14000000',
    weight: '5,972E24',
    type: 'blue',
    star: 'Pollux',
    resources: '50%',
    cost: '8',
    img: 'https://officialpsds.com/imageview/7l/0l/7l0lm0_large.png?1521316541',
    value: 'quadrillion',
  },
  {
    id: 13,
    title: 'Euterpe',
    age: '12000000',
    weight: '7,972E24',
    type: 'green',
    star: 'Alhena',
    resources: '30%',
    cost: '2',
    img: 'https://png.monster/wp-content/uploads/2022/07/png.monster-843.png',
    value: 'quadrillion',
  },
  {
    id: 14,
    title: 'Phocaea',
    age: '11000000',
    weight: '8,972E24',
    type: 'blue',
    star: 'Wasat',
    resources: '20%',
    cost: '3',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Populated_Planet.png/1024px-Populated_Planet.png',
    value: 'billion',
  },
  {
    id: 15,
    title: 'Kalliope',
    age: '10000000',
    weight: '9,972E24',
    type: 'red',
    star: 'Mebsuta',
    resources: '10%',
    cost: '4',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ice_planet.png/1200px-Ice_planet.png',
    value: 'million',
  },
  {
    id: 16,
    title: 'Lutetia',
    age: '9000000',
    weight: '10,972E24',
    type: 'green',
    star: 'Mekbuda',
    resources: '60%',
    cost: '5',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Gajillion_Islands_Planet.png',
    value: 'billion',
  },
  {
    id: 17,
    title: 'Massalia',
    age: '8000000',
    weight: '11,972E24',
    type: 'blue',
    star: 'Propus',
    resources: '70%',
    cost: '6',
    img: 'https://images.pngnice.com/download/2007/Space-Planet-PNG-Photos.png',
    value: 'quadrillion',
  },
  {
    id: 18,
    title: 'Thetis',
    age: '7000000',
    weight: '12,972E24',
    type: 'red',
    star: 'Tejat',
    resources: '80%',
    cost: '7',
    img: 'https://www.pngkit.com/png/full/288-2881214_1-photos-sci-fi-planet-png.png',
    value: 'billion',
  },
  {
    id: 19,
    title: 'Psyche',
    age: '6000000',
    weight: '13,972E24',
    type: 'green',
    star: 'Jishui',
    resources: '90%',
    cost: '8',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Bringer_of_War_Planet.png',
    value: 'million',
  },
  {
    id: 20,
    title: 'Irene',
    age: '5000000',
    weight: '14,972E24',
    type: 'blue',
    star: 'Intercrus',
    resources: '100%',
    cost: '9',
    img: 'https://pngimg.com/uploads/mars_planet/mars_planet_PNG28.png',
    value: 'billion',
  },
  {
    id: 21,
    title: 'Eunomia',
    age: '8000000',
    weight: '11,972E24',
    type: 'blue',
    star: 'Dubhe',
    resources: '70%',
    cost: '6',
    img: 'https://images.pngnice.com/download/2007/Space-Planet-PNG-Photos.png',
    value: 'quadrillion',
  },
]